### ISSUE TITLE
Showplan for WordPress 5.5.3 will be further developed for PHP 7.4 ?

### ISSUE THREAD

**Issue by Radio-Quergedacht** [InsanityRadio/Showplan#4]
Showplan for WordPress 5.5.3 will be further developed for PHP 7.4 ?

**Comment by Jamie0** [comment]
Sadly, we stopped using (and hence developing) Showplan after trying repeatedly to get it approved for the plugin directory. 

We still have it activated on a number of sites running the latest WordPress, so it seems broadly compatible. 

If there's a particular error that happens on later versions of PHP, please open another issue with the error message, which should be in the web server error.log.
